### ISSUE TITLE
Combining LSP4E and Xtext into a .jar File [to Run in Eclipse Che as an LS Sidecar]

### ISSUE THREAD

**Issue by SharkJ** [svenefftinge/xtext-lsp-workshop#19]
Hi,
Thanks for the post! It is very informative.
I'm trying to build a language server sidecar for eclipse che, where the LS is created using Xtext. I have, so far, achieved up to the point where the LS is implemented to Che by embedding my LS (.jar file) in a Dockerfile and uploading to Docker Hub. The LS works fine with Che and it performs auto-completion and error recognition.

However, what does not work as expected is Syntax Highlighting. Though Xtext provides syntax highlighting support when I implement the Xtext DSL as an Eclipse plugin, it does not do so when implemented it in Che. From what I know, this is because LSP has problems supporting this feature in custom DSLs.

Why I decided to raise the issue in this repo is because AFAIK, Che/LSP supports TextMate. Therefore, I was wondering whether you'd be able to explain if there's a way to package (create a shadowJar using Gradle) the Xtext DSL along with the LSP4E support (where the TextMate grammar is defined) so that I could use the combined binary file it to run as the LS in Eclipse Che.

Thanks in advance!

**Comment by svenefftinge** [comment]
LSP in general doesn't support syntax coloring. 
You need to configure the editor appropriately. 
I didn't know Che supports Textmate, do you have a reference?

**Comment by SharkJ** [comment]
> I didn't know Che supports Textmate, do you have a reference?

I'm sorry, it was my mistake. Che gets support from Orion Editor for syntax highlighting.
I'll open an issue in the Che repo inquiring about getting support from Orion.
Thank You!
